import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [members, setMembers] = useState([]);
  const [name, setName] = useState("");
  const [role, setRole] = useState("");
  const [socialMediaUrl, setSocialMediaUrl] = useState("");
  const [description, setDescription] = useState("");
  const [imgUrl, setImgUrl] = useState("");

  useEffect(() => {
    axios
      .get("http://localhost:3333/members")
      .then((response) => {
        console.log(response);
        setMembers(response.data);
      })
      .catch((err) => console.log(err));
  }, []);

  function handleSubmit() {
    if (!name || !role || !socialMediaUrl || !description || !imgUrl) {
      alert("Please fill all the inputs.");
      return;
    }
    axios
      .post("http://localhost:3333/members", {
        name,
        role,
        socialMediaUrl,
        description,
        imgUrl,
      })
      .then((response) => {
        console.log(response);
        alert("Member successfully registered!");
      })
      .catch((err) => console.log(err));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Mouse Haunt CMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Mouse Haunt CMS!</h1>
        <p>Add new member</p>
        <input
          placeholder="Name"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
        <input
          placeholder="Role"
          value={role}
          onChange={(e) => setRole(e.target.value)}
        />
        <input
          placeholder="Social media url"
          value={socialMediaUrl}
          onChange={(e) => setSocialMediaUrl(e.target.value)}
        />
        <input
          placeholder="Description"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
        />
        <input
          placeholder="Image url"
          value={imgUrl}
          onChange={(e) => setImgUrl(e.target.value)}
        />
        <button className="submitButton" type="button" onClick={handleSubmit}>
          Submit
        </button>
        <p>These are our current members:</p>
        <div style={{ display: "flex" }}>
          {members.map((member: any) => (
            <div
              key={member._id}
              style={{
                border: "1px solid #fff",
                padding: 20,
                borderRadius: 10,
                margin: 10,
                width: 200,
              }}
            >
              <p>{member.name}</p>
              <p>{member.role}</p>
              <p>{member.socialMediaUrl}</p>
              <p>{member.description}</p>
              <p>{member.imgUrl}</p>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}>Mouse Haunt</span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
